In [ ]:
%reload_ext autoreload
%autoreload 2

In [ ]:
from peptdeep.model.charge import *
import pandas as pd

model = ChargeModelForAASeq(min_charge=1, max_charge=2)

seq_df = pd.DataFrame({
    'sequence': ['ABCDE','FGHIJK','LMNOPQ','RSTUVWXYZ','HIJKL'],
    'charge_indicators': [[1,0],[0,1],[1,1],[0,0],[0,0]],
})
model.train(seq_df)
model.predict_and_clip_charges(
    seq_df, 
    min_precursor_charge=model.min_predict_charge,
    max_precursor_charge=model.max_predict_charge,
    charge_prob_cutoff=0.3
)

OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.

Predicting with multiprocessing ...

  0%|          | 0/1 [00:00<?, ?it/s]OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
100%|██████████| 1/1 [00:03<00:00,  3.26s/it]

  sequence charge_indicators  nAA  charge_prob  charge
0    ABCDE            [1, 0]    5     0.725907       1
1    HIJKL            [0, 0]    5     0.304970       2
2   FGHIJK            [0, 1]    6     0.376047       2
3   LMNOPQ            [1, 1]    6     0.611807       1
4   LMNOPQ            [1, 1]    6     0.434347       2

In [ ]:
model.predict_charges_as_prob(seq_df, 2, 4)

Predicting with multiprocessing ...

  0%|          | 0/1 [00:00<?, ?it/s]OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
100%|██████████| 1/1 [00:03<00:00,  3.14s/it]

    sequence charge_indicators  nAA  charge_prob  charge
0      ABCDE            [1, 0]    5     0.297068       2
1      HIJKL            [0, 0]    5     0.304970       2
2     FGHIJK            [0, 1]    6     0.376047       2
3     LMNOPQ            [1, 1]    6     0.434347       2
4  RSTUVWXYZ            [0, 0]    9     0.206633       2

In [ ]:
seq_df['charge'] = 1
model.predict_prob_for_charge(seq_df)

Predicting with multiprocessing ...

  0%|          | 0/1 [00:00<?, ?it/s]OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
100%|██████████| 1/1 [00:03<00:00,  3.18s/it]

    sequence charge_indicators  nAA  charge  charge_prob
0      ABCDE            [1, 0]    5       1     0.725907
1      HIJKL            [0, 0]    5       1     0.131404
2     FGHIJK            [0, 1]    6       1     0.126947
3     LMNOPQ            [1, 1]    6       1     0.611807
4  RSTUVWXYZ            [0, 0]    9       1     0.162039

In [ ]:
from peptdeep.model.charge import *
import pandas as pd

model = ChargeModelForModAASeq(min_charge=1, max_charge=2)

modseq_df = pd.DataFrame({
    'sequence': ['ABCDE','FGHIJK','LMNOPQ','RSTUVWXYZ'],
    'mods': ['', '', 'Oxidation@M', 'Phospho@T'],
    'mod_sites': ['', '', '2', '3'],
    'charge_indicators': [[1,0],[0,1],[1,1],[0,0]],
})
model.train(modseq_df)
model.predict_and_clip_charges(
    modseq_df, 
    min_precursor_charge=model.min_predict_charge,
    max_precursor_charge=model.max_predict_charge,
    charge_prob_cutoff=0.3
)

Predicting with multiprocessing ...

  0%|          | 0/1 [00:00<?, ?it/s]OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
100%|██████████| 1/1 [00:03<00:00,  3.20s/it]

  sequence         mods mod_sites charge_indicators  nAA  charge_prob  charge
0    ABCDE                                   [1, 0]    5     0.733565       1
1   FGHIJK                                   [0, 1]    6     0.350178       1
2   FGHIJK                                   [0, 1]    6     0.650386       2
3   LMNOPQ  Oxidation@M         2            [1, 1]    6     0.742781       1
4   LMNOPQ  Oxidation@M         2            [1, 1]    6     0.617950       2

In [ ]:
model.predict_charges_as_prob(modseq_df, 2, 4)

Predicting with multiprocessing ...

  0%|          | 0/1 [00:00<?, ?it/s]OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
100%|██████████| 1/1 [00:03<00:00,  3.23s/it]

,sequence,mods,mod_sites,charge_indicators,nAA,charge_prob,charge
0,ABCDE,,,"[1, 0]",5,0.244911,2
1,FGHIJK,,,"[0, 1]",6,0.650386,2
2,LMNOPQ,Oxidation@M,2,"[1, 1]",6,0.617950,2
3,RSTUVWXYZ,Phospho@T,3,"[0, 0]",9,0.228520,2

In [ ]:
modseq_df['charge'] = 1
model.predict_prob_for_charge(modseq_df)

Predicting with multiprocessing ...

  0%|          | 0/1 [00:00<?, ?it/s]OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
100%|██████████| 1/1 [00:03<00:00,  3.35s/it]

,sequence,mods,mod_sites,charge_indicators,nAA,charge,charge_prob
0,ABCDE,,,"[1, 0]",5,1,0.733565
1,FGHIJK,,,"[0, 1]",6,1,0.350178
2,LMNOPQ,Oxidation@M,2,"[1, 1]",6,1,0.742781
3,RSTUVWXYZ,Phospho@T,3,"[0, 0]",9,1,0.294222